version: '3.8'

services:
  proof-server:
    container_name: 'proof-server'
    image: 'midnightnetwork/proof-server:3.0.7'
    ports:
      - "6300:6300"
    environment:
      RUST_BACKTRACE: "full"
    networks:
      - midnight-network

  indexer:
    container_name: 'indexer'
    image: 'midnightnetwork/midnight-pubsub-indexer:2.3.0'
    platform: linux/amd64
    ports:
      - '8088:8088'
    command: ['-Dlogback.configurationFile=logback-json-file.xml']
    environment:
      LOG_LEVEL: 'TRACE'
      LEDGER_NETWORK_ID: 'Undeployed'
      SUBSTRATE_NODE_WS_URL: 'ws://node:9944'
      OTEL_JAVAAGENT_ENABLED: 'false'
    healthcheck:
      test: ['CMD', 'egrep', '"Block .* was stored at height 0"', '/tmp/app_logs/server.log']
      interval: 5s
      timeout: 5s
      retries: 30
    depends_on:
      node:
        condition: service_started
    networks:
      - midnight-network

  node:
    image: 'midnightnetwork/midnight-node:0.8.0'
    platform: linux/amd64
    container_name: 'node'
    ports:
      - "9944:9944"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9944/health" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 40s
    environment:
      CFG_PRESET: "dev"
    networks:
      - midnight-network

  # MCP integration tests
  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - TEST_NETWORK_ID=Undeployed
      # If set to true, will skip integration tests that require network
      - SKIP_INTEGRATION_TESTS=${SKIP_INTEGRATION_TESTS:-false}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: yarn test:integration
    depends_on:
      midnight-node:
        condition: service_healthy
      proof-server:
        condition: service_healthy
      indexer:
        condition: service_healthy
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  midnight-node-data:
  node_modules: 